Tivote/Models/Admin/Role.cs
using System;
using System.ComponentModel;

namespace Tivote.Models.Admin
{
    public class Role : Entity
    {
        [DisplayName("نام نقش")]
        public string Name { get; set; } = string.Empty;
        [DisplayName("مجوزها")]
        public List<Permission> Permissions { get; set; } = new();
    }
}

Tivote/Models/Admin/User.cs
using System;
using System.ComponentModel;

namespace Tivote.Models.Admin
{
    public class User : Entity
    {
        [DisplayName("نام کاربری")]
        public string Name { get; set; } = string.Empty;
        public Contact? Contact { get; set; } = default!;
        public IEnumerable<Role> Roles { get; set; } = default!;
    }
}

Tivote/ViewComponents/ModalViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace TivPortal.ViewComponents
{
    public class ModalViewComponent : ViewComponent
    {
        
        public async Task<IViewComponentResult> InvokeAsync(string title,string action,object model)
        {
            ModalPath path = new(title,action,model);
            return View(path);
        }
        public class ModalPath
        {
            public ModalPath(string title,string action,object model)
            {
                Title = title;
                Action = action;
                Model = model;
            }
            public string Title { get; set; } = string.Empty;
            public string Action { get; set; } = string.Empty;
            public object Model { get; set; } = default!;
        }
    }
}

Tivote/ViewComponents/SidebarMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tivote.ViewComponents
{
    public class SidebarMenuViewComponent : ViewComponent
    {
        public SidebarMenuViewComponent()
        {
        }
        public List<SidebarMenuItem> MenuItems { get; set; } = new();
        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<SidebarMenuItem> menuItems)
        {
            foreach (var item in menuItems)
            {
                MenuItems.Add(item);
            }
            return View("Default", MenuItems);
        }
        public class SidebarMenuItem
        {
            public string Area { get; set; } = string.Empty;
            public string Controller { get; set; } = string.Empty;
            public string Action { get; set; } = string.Empty;
            public string Text { get; set; } = string.Empty;
            public string Target { get; set; } = string.Empty;
            public bool Modal { get; set; }
        }
    }
}

Tivote/Views/Admin/AdminLayout.cshtml
@using static Tivote.ViewComponents.SidebarMenuViewComponent
@{
    Layout = "_Layout";
}
<div class="row">
    <div class="col col-3">
        @{
            List<SidebarMenuItem> menuItems = new List<SidebarMenuItem>()
        {
        new SidebarMenuItem() { Area="",Controller="Admin",Action="Index",Text="کاربران"},
        new SidebarMenuItem() { Area="",Controller="Admin",Action="EditRoles",Text="نقشهای کاربری"},
        new SidebarMenuItem() { Area="",Controller="Admin",Action="Permissions",Text="مجوزها"},
        new SidebarMenuItem() { Area="",Controller="Admin",Action="Permissions",Text="مجوزهای نقش"},
        new SidebarMenuItem() { Area="",Controller="Admin",Action="UserRoles",Text="نقشهای کاربران"}
        };
        }
        @await Component.InvokeAsync("SidebarMenu",menuItems)
    </div>
    @{
        TivPortal.ViewComponents.ModalViewComponent.ModalPath? modalPath = ViewBag.Modal as TivPortal.ViewComponents.ModalViewComponent.ModalPath;
        if (modalPath is not null)
        {
            @await Component.InvokeAsync("Modal", new
    {
    Title = modalPath.Title,
    Action = modalPath.Action,
    Model = modalPath.Model
    }
    )
        }
    }
    <div class="col col-9">
        @RenderBody()
    </div>
</div>

Tivote/Views/Admin/CreateRole.cshtml
@model Role

<div class="modal fade" tabindex="-1" role="dialog" id="createRole">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">افزودن نقش کاربری</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="btn btn-close btn-danger" aria-hidden="true" />
                </button>
            </div>
            <form asp-action="CreateRole" enctype="multipart/form-data">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button data-toggle="ajax-modal" data-target="#createRole" data-url="@Url.Action("CreateRole")" type="submit" class="btn btn-primary">ذخیره</button>
                        <button data-dismiss="modal" id="cancel" class="btn btn-danger" type="button">انصراف</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Tivote/Views/Admin/EditRoles.cshtml
@model Tivote.Models.Admin.User
<p>@Model.Name</p>

Tivote/Views/Admin/Index.cshtml
@model IEnumerable<User>
@{
    Layout = "AdminLayout";
}
<table class="w-100 table table-striped">
    <thead>
        <tr>
            <th>
                نام خانوادگی و نام
            </th>
            <th>
                نام کاربری
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    @{
                        if (item.Contact != null)
                        {
                            <td>
                                @item.Contact.LastName @item.Contact.FirstName
                            </td>
                        }
                        else
                        {
                            <td>
                                ---
                            </td>
                        }
                        <td>
                            @item.Name
                        </td>
                    }
                </tr>
            }
        }
    </tbody>
</table>

Tivote/Views/Admin/Roles.cshtml
@model IEnumerable<Role>
<table>
    @{
        foreach (Role role in Model)
        {
            <tr>
                <td>
                    @role.Name
                </td>
            </tr>
        }

    }

</table>
<a data-toggle="ajax-modal" data-target="#createRole" data-url="@Url.Action("CreateRole")" class="btn btn-primary w-100 ">افزودن نقش کاربری جدید</a>

Tivote/Views/Admin/Users.cshtml
@model IEnumerable<User>

<table>
    @{
        foreach (User user in Model)
        {
            <tr>
                <td>
                    @user.Name
                </td>
            </tr>
        }

    }

</table>