Tivote/Models/Contact.cs
using System.ComponentModel;
using Tivote.Models.Admin;

namespace Tivote.Models
{
    public class Contact : Entity
    {
        public Title Title { get; set; } = default!;
        [DisplayName("نام")]
        public string FirstName { get; set; } = string.Empty;
        [DisplayName("نام خانوادگی")]
        public string LastName { get; set; } = string.Empty;
        [DisplayName("شماره داخلی")]
        public string Number { get; set; } = string.Empty;
        [DisplayName("ایمیل")]
        public string Email { get; set; } = string.Empty;
        [DisplayName("شماره پرسنلی")]
        public string PersonelNumber { get; set; } = string.Empty;
        [DisplayName("محل استقرار")]
        public Location Location { get; set; } = default!;
        [DisplayName("واحد")]
        public Department Department { get; set; } = default!;
    }
}

Tivote/Models/ViewModels/SearchContact.cs
using Tivote.Models.Admin;

namespace Tivote.Models.ViewModels
{
    public class SearchContact
    {
        public string SearchText { get; set; } = string.Empty;
        public List<Contact> SerchResult { get; set; } = new();
    }
}

Tivote/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tivote.Data;
using Tivote.Models;
using Tivote.Models.Admin;
using Tivote.Models.ViewModels;
using TivPortal.ViewComponents;

namespace Tivote.Controllers
{
    public class ContactsController : MainController
    {
        public ContactsController(TivoteDb context) : base(context)
        {
        }
        public async Task<IActionResult> Index()
        {
            CurrentUrl.Action = "Index";
            CurrentUrl.Model = await Context.Departments.Include(d => d.Contacts).ThenInclude(c => c.Location).ToListAsync();
            return View(CurrentUrl.Model);
        }
        public async Task<IActionResult> GroupByLocations()
        {
            CurrentUrl.Action = "GroupByLocations";
            CurrentUrl.Model = await Context.Locations.Include(l => l.Contacts).ThenInclude(c => c.Department).ToListAsync();
            return View(CurrentUrl.Model);
        }
        public async Task<IActionResult> GroupByLastName()
        {
            CurrentUrl.Action = "Index";
            CurrentUrl.Model = await Context.Locations.Include(l => l.Contacts).ThenInclude(c => c.Department).ToListAsync();
            return View(CurrentUrl.Model);
        }
        public IActionResult SearchContact()
        {
            SearchContact searchContact = new();
            return View(searchContact);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchContact([Bind("SearchText")] SearchContact searchContact)
        {
            if (ModelState.IsValid)
            {
                _ = await Context.Departments.ToListAsync();
                _ = await Context.Locations.ToListAsync();
                searchContact.SearchText = searchContact.SearchText.ToLower();
                IEnumerable<Contact> contacts = await Context.Contacts
                    .Where(c => c.FirstName.ToLower().Contains(searchContact.SearchText) ||
                                c.LastName.ToLower().Contains(searchContact.SearchText) ||
                                c.Email.ToLower().Contains(searchContact.SearchText) ||
                                c.Number.ToLower().Contains(searchContact.SearchText)||
                                c.Department.Name.ToLower().Contains(searchContact.SearchText)||
                                c.Location.Name.ToLower().Contains(searchContact.SearchText))
                    .ToListAsync();
                searchContact.SerchResult.AddRange(contacts);
            }
            return View(searchContact);
        }
        public IActionResult CreateLocation()
        {
            Location location = new();
            ViewBag.Modal = new ModalViewComponent.ModalPath("افزودن محل استقرار", "CreateLocation", location);
            return View(CurrentUrl.Action, CurrentUrl.Model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLocation([Bind("Name,Id")] Location location)
        {
            if (ModelState.IsValid)
            {
                Context.Locations.Add(location);
                await Context.SaveChangesAsync();
                ViewBag.Modal = null;
                return RedirectToAction(CurrentUrl.Action);
            }
            ViewBag.Modal = new ModalViewComponent.ModalPath("افزودن محل استقرار", "CreateLocation", location);
            return View(CurrentUrl.Action, CurrentUrl.Model);
        }
        public IActionResult CreateDepartment()
        {
            Department department = new();
            ViewBag.Modal = new ModalViewComponent.ModalPath("افزودن مجموعه سازمانی", "CreateDepartment", department);
            return View(CurrentUrl.Action, CurrentUrl.Model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDepartment([Bind("Name,Id")] Department department)
        {
            if (ModelState.IsValid)
            {
                department.Id = Guid.NewGuid();
                Context.Departments.Add(department);
                await Context.SaveChangesAsync();
                ViewBag.Modal = null;
                return RedirectToAction(CurrentUrl.Action);
            }
            IEnumerable<Department> departments = await Context.Departments.Include(d => d.Contacts).ThenInclude(c => c.Location).ToListAsync();
            ViewBag.Modal = new ModalViewComponent.ModalPath("افزودن محل استقرار", "CreateDepartment", department);
            return View(CurrentUrl.Action, CurrentUrl.Model);
        }
        public void SetTitles()
        {
            IEnumerable<Title> titles = Context.Titles.ToList();
            SelectListItem[] titlesItems = new SelectListItem[titles.Count()];
            for (int i = 0; i < titles.Count(); i++)
            {
                titlesItems[i] = new SelectListItem { Value = titles.ElementAt(i).Id.ToString(), Text = titles.ElementAt(i).Name };
            }
            ViewData["TitleId"] = titlesItems;
        }
        public void SetDepartments()
        {
            IEnumerable<Department> departments = Context.Departments.ToList();
            SelectListItem[] departmentsItems = new SelectListItem[departments.Count()];
            for (int i = 0; i < departments.Count(); i++)
            {
                departmentsItems[i] = new SelectListItem { Value = departments.ElementAt(i).Id.ToString(), Text = departments.ElementAt(i).Name };
            }
            ViewData["DepartmentId"] = departmentsItems;
        }
        public void SetLocations()
        {
            IEnumerable<Location> locations = Context.Locations.ToList();
            SelectListItem[] locationsItems = new SelectListItem[locations.Count()];
            for (int i = 0; i < locations.Count(); i++)
            {
                locationsItems[i] = new SelectListItem { Value = locations.ElementAt(i).Id.ToString(), Text = locations.ElementAt(i).Name };
            }
            ViewData["LocationId"] = locationsItems;
        }
        

        public async Task<IActionResult> EditContact(Guid id)
        {
            SetTitles();
            SetDepartments();
            SetLocations();
            Contact? contact = await Context.Contacts.Include(c => c.Title).Include(c => c.Department).Include(c => c.Location).FirstOrDefaultAsync(c => c.Id == id);
            if (contact == null)
            {
                return NotFound();
            }
            ContactDto contactDto = new()
            {
                Id = contact.Id,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Email = contact.Email,
                Number = contact.Number,
                DepartmentId = contact.Department.Id,
                LocationId = contact.Location.Id,
                TitleId = contact.Title.Id
            };
            ViewBag.Modal = new ModalViewComponent.ModalPath("ویرایش اطلاعات تماس", "CreateContact", contactDto);
            IEnumerable<Department> departments = await Context.Departments.Include(d => d.Contacts).ThenInclude(c => c.Location).ToListAsync();
            return View("Index", departments);
        }
        public IActionResult CreateContact()
        {
            SetTitles();
            SetDepartments();
            SetLocations();
            ContactDto contactDto = new();
            ViewBag.Modal = new ModalViewComponent.ModalPath("افزودن اطلاعات تماس", "CreateContact", contactDto);
            return View(CurrentUrl.Action, CurrentUrl.Model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateContact(ContactDto contactDto)
        {
            if (ModelState.IsValid)
            {
                Department? department = await Context.Departments.FindAsync(contactDto.DepartmentId);
                Location? location = await Context.Locations.FindAsync(contactDto.LocationId);
                Title? title = await Context.Titles.FindAsync(contactDto.TitleId);
                if (department == null || location == null || title == null)
                {
                    return NotFound();
                }
                Contact contact = new()
                {
                    FirstName = contactDto.FirstName,
                    LastName = contactDto.LastName,
                    Number = contactDto.Number,
                    Email = contactDto.Email,
                    Department = department,
                    Location = location,
                    Title = title
                };
                if (contactDto.Id == Guid.Empty)
                {
                    contact.Id = Guid.NewGuid();
                    Context.Contacts.Add(contact);
                }
                else
                {
                    contact.Id = contactDto.Id;
                    Context.Contacts.Update(contact);
                }
                await Context.SaveChangesAsync();
                ViewBag.Modal = null;
                string username = "SJSCO\\" + contact.Email.Split('@')[0];
                User? user = await Context.Users.Include(u => u.Contact).FirstOrDefaultAsync(u => u.Name == username);
                if (user == null)
                {
                    user = new User
                    {
                        Name = username,
                    };
                    user.Contact = contact;
                    Context.Users.Add(user);
                    await Context.SaveChangesAsync();
                }
                else
                {
                    if(user.Contact is null)
                        user.Contact = contact;
                    Context.Users.Update(user);
                    await Context.SaveChangesAsync();
                }
                return RedirectToAction(CurrentUrl.Action);
            }
            SetTitles();
            SetDepartments();

Tivote/ViewComponents/ModalViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace TivPortal.ViewComponents
{
    public class ModalViewComponent : ViewComponent
    {
        
        public async Task<IViewComponentResult> InvokeAsync(string title,string action,object model)
        {
            ModalPath path = new(title,action,model);
            return View(path);
        }
        public class ModalPath
        {
            public ModalPath(string title,string action,object model)
            {
                Title = title;
                Action = action;
                Model = model;
            }
            public string Title { get; set; } = string.Empty;
            public string Action { get; set; } = string.Empty;
            public object Model { get; set; } = default!;
        }
    }
}

Tivote/Views/Contacts/ContactsLayout.cshtml
@{
    Layout = "_Layout";
}
<div class="row">
    <div class="col col-3 rounded-4 bg-light">
        <a asp-area="" asp-controller="Contacts" asp-action="Index" class="btn btn-primary w-100">دسته بندی با مجموعه سازمانی</a>
        <hr />
        <a asp-area="" asp-controller="Contacts" asp-action="GroupByLocations" class="btn btn-primary w-100">دسته بندی با مکان استقرار</a>
        <hr />
        <a asp-area="" asp-controller="Contacts" asp-action="GroupByLastName" class="btn btn-primary w-100">دسته بندی با نام خانوادگی</a>
        <hr />
        @*<a data-toggle="ajax-modal" data-target="#createContact" data-url="@Url.Action("CreateContact")" class="btn btn-primary w-100">ایجاد اطلاعات تماس</a>*@
        <a asp-action="CreateContact" class="btn btn-primary w-100">ایجاد اطلاعات تماس</a>
        <hr />
        <a asp-action="CreateDepartment" class="btn btn-primary w-100">ایجاد مجموعه سازمانی</a>
        <hr />
        <a asp-action="CreateLocation" class="btn btn-primary w-100">ایجاد مکان استقرار</a>
        <hr />
        <a asp-area="" asp-controller="Contacts" asp-action="SearchContact" class="btn btn-primary w-100">جستجو</a>
    </div>
    <div class="col col-9 rounded-4" style="height:100%;">
        @{
            TivPortal.ViewComponents.ModalViewComponent.ModalPath? modalPath = ViewBag.Modal as TivPortal.ViewComponents.ModalViewComponent.ModalPath;
            if (modalPath is not null)
            {
                @await Component.InvokeAsync("Modal", new
        {
        Title = modalPath.Title,
        Action = modalPath.Action,
        Model = modalPath.Model
        }
        )
            }
        }
        @RenderBody()
    </div>
</div>
@section scripts{
    <script>
        $('body').on('click', '.modal-link', function () {
            var actionUrl = $(this).attr('href');
            $.get(actionUrl).done(function (data) {
                $('body').find('.modal-content').html(data);
            });
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });

        $('body').on('click', '.relative', function (e) {
            e.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var dataToSend = form.serialize();
            $.post(actionUrl, dataToSend).done(function (data) {
                $('body').find('.modal-content').html(data);
            });
        })

        $('body').on('click', '.close', function () {
            $('body').find('#modal-container').modal('hide');
        });

        $('#CancelModal').on('click', function () {
            return false;
        });
    </script>
}
    @await RenderSectionAsync("Scripts", required: false)

Tivote/Views/Contacts/CreateContact.cshtml
@model Tivote.Models.ViewModels.ContactDto
@{
    ViewData["Title"] = "ایجاد تماس";
}

<hr />
@{
    SelectListItem[]? departments = ViewData["DepartmentId"] as SelectListItem[];
    SelectListItem[]? locations = ViewData["LocationId"] as SelectListItem[];
    SelectListItem[]? titles = ViewData["TitleId"] as SelectListItem[];

}
@{
    if (departments == null)
    {
    <p>"جدول مجموعه سازمانی خالی است."</p>
    }
}
@{
    if (locations == null)
    {
    <p>"جدول مکانهای استقرار خالی است."</p>
    }
}

<form asp-action="CreateContact">
    <div class="modal-body">
        <input type="hidden" asp-for="Id" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <label asp-for="TitleId" class="control-label"></label>
        <select asp-for="TitleId" asp-items="@titles" class="form-control"></select>
        <div class="form-group">
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Number" class="control-label"></label>
            <input asp-for="Number" class="form-control" />
            <span asp-validation-for="Number" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <hr />
        <label asp-for="DepartmentId" class="control-label"></label>
        <select asp-for="DepartmentId" asp-items="@departments" class="form-control"></select>
        <hr />
        <label asp-for="LocationId" class="control-label"></label>
        <select asp-for="LocationId" asp-items="@locations" class="form-control"></select>
        <hr />
    </div>
    <div class="modal-footer">
        <div class="form-group">
            <button type="submit" class="btn btn-primary">ذخیره</button>
            <a asp-action="CloseModal" class="btn btn-secondary">انصراف</a>
        </div>
    </div>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Tivote/Views/Contacts/CreateDepartment.cshtml
@model Department
@{
    ViewData["Title"] = "ایجاد مجموعه سازمانی";
}

<form asp-action="CreateDepartment">
    <div class="modal-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">ذخیره</button>
                <a asp-action="CloseModal" class="btn btn-secondary">انصراف</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Tivote/Views/Contacts/CreateLocation.cshtml
@model Location
@{
    ViewData["Title"] = "ایجاد مکان استقرار";
}

<form asp-action="CreateLocation">
    <div class="modal-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="modal-footer">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">ذخیره</button>
                <a asp-action="CloseModal" class="btn btn-secondary">انصراف</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Tivote/Views/Contacts/Edit.cshtml
<div id="modal-container" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
</div>
<a href="@Url.Action("CreateEdit", new { controller = "Contacts", issueid = "1", addedit = "add" })" class="modal-link btn btn-success">Add New Status</a>


@section scripts{
    <script>
        $('body').on('click', '.modal-link', function () {
            var actionUrl = $(this).attr('href');
            $.get(actionUrl).done(function (data) {
                $('body').find('.modal-content').html(data);
            });
            $(this).attr('data-target', '#modal-container');
            $(this).attr('data-toggle', 'modal');
        });

        $('body').on('click', '.relative', function (e) {
            e.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var dataToSend = form.serialize();
            $.post(actionUrl, dataToSend).done(function (data) {
                $('body').find('.modal-content').html(data);
            });
        })

        $('body').on('click', '.close', function () {
            $('body').find('#modal-container').modal('hide');
        });

        $('#CancelModal').on('click', function () {
            return false;
        });
    </script>
}

Tivote/Views/Contacts/GroupByLastName.cshtml
@model Dictionary<string,List<Contact>>
@{
    Layout = "ContactsLayout";
}
@{
    ViewData["Title"] = "اطلاعات تماس-دسته بندی با واحد";
}
<div class="accordion" id="DepartmentAccordion">
    @{
        string heading;
        string target;
        string controls;
        int i = 0;
        foreach (var item in Model.Keys)
        {
            i++;
            heading = "Heading" + i.ToString().Trim();
            target = "#Collapse" + i.ToString().Trim();
            controls = "Collapse" + i.ToString().Trim();
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target=@target aria-expanded="true" aria-controls=@controls style="font-family: KalamehWebFaNum;">
                        @item
                    </button>
                </h2>
                <div id=@controls class="accordion-collapse collapse show" aria-labelledby=@heading data-bs-parent="#DepartmentAccordion" style="font-family: KalamehWebFaNum;">
                    <div class="accordion-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        نام و نام خانوادگی
                                    </th>
                                    <th>
                                        شماره
                                    </th>
                                    <th>
                                        پست الکترونیک
                                    </th>
                                    <th>
                                        مکان استقرار
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    foreach (var contact in Model[item])
                                    {
                                        <tr>
                                            <td>
                                                @contact.LastName @contact.FirstName
                                            </td>
                                            <td>
                                                @contact.Number
                                            </td>
                                            <td>
                                                @contact.Email
                                            </td>
                                            <td>
                                                @contact.Location.Name
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
    }

</div>

Tivote/Views/Contacts/GroupByLocations.cshtml
@model IEnumerable<Location>
@{
    Layout = "ContactsLayout";
}
@{
    ViewData["Title"] = "اطلاعات تماس-دسته بندی با محل استقرار";
}
<div class="accordion" id="DepartmentAccordion">
    @{
        string heading;
        string target;
        string controls;

        int i = 0;
        foreach (var item in Model)
        {
            i++;
            heading = "Heading" + i.ToString().Trim();
            target = "#Collapse" + i.ToString().Trim();
            controls = "Collapse" + i.ToString().Trim();
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target=@target aria-expanded="true" aria-controls=@controls style="font-family: KalamehWebFaNum;">
                        @item.Name
                    </button>
                </h2>
                <div id=@controls class="accordion-collapse collapse show" aria-labelledby=@heading data-bs-parent="#DepartmentAccordion" style="font-family: KalamehWebFaNum;">
                    <div class="accordion-body">
                        @if (@item.Contacts.Count > 0)
                        {
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            نام و نام خانوادگی
                                        </th>
                                        <th>
                                            شماره
                                        </th>
                                        <th>
                                            پست الکترونیک
                                        </th>
                                        <th>
                                            واحد
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        foreach (var contact in item.Contacts)
                                        {
                                            <tr>
                                                <td>
                                                    @contact.FirstName @contact.LastName
                                                </td>
                                                <td>
                                                    @contact.Number
                                                </td>
                                                <td>
                                                    @contact.Email
                                                </td>
                                                <td>
                                                    @contact.Department.Name
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                </div>
            </div>
        }
    }

</div>

Tivote/Views/Contacts/Index.cshtml
@model IEnumerable<Department>
@{
    Layout = "ContactsLayout";
}
@{
    ViewData["Title"] = "اطلاعات تماس-دسته بندی با واحد";
}

<div class="accordion" id="DepartmentAccordion">
    @{
        string heading;
        string target;
        string controls;

        int i = 0;
        foreach (var item in Model)
        {
            i++;
            heading = "Heading" + i.ToString().Trim();
            target = "#Collapse" + i.ToString().Trim();
            controls = "Collapse" + i.ToString().Trim();
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingOne">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target=@target aria-expanded="true" aria-controls=@controls style="font-family: KalamehWebFaNum;">
                                @item.Name
                            </button>
                        </h2>
                        <div id=@controls class="accordion-collapse collapse show" aria-labelledby=@heading data-bs-parent="#DepartmentAccordion" style="font-family: KalamehWebFaNum;">
                            <div class="accordion-body">
                                @if (@item.Contacts.Count > 0)
                        {
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>
                                                    نام و نام خانوادگی
                                                </th>
                                                <th>
                                                    شماره
                                                </th>
                                                <th>
                                                    پست الکترونیک
                                                </th>
                                                <th>
                                                    مکان استقرار
                                                </th>
                                            <th>
                                                عملیات
                                            </th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                        foreach (var contact in item.Contacts)
                                        {
                                                            <tr>
                                                                <td>
                                                                    @contact.LastName @contact.FirstName
                                                                </td>
                                                                <td>
                                                                    @contact.Number
                                                                </td>
                                                                <td>
                                                                    @contact.Email
                                                                </td>
                                                                <td>
                                                                    @contact.Location.Name
                                                                </td>
                                                <td>
                                                    <a asp-action="EditContact" class="btn btn-primary" asp-route-id="@contact.Id">ویرایش</a>
                                                </td>
                                                                <td>
                                                                </td>
                                                            </tr>
                                        }
                                            }
                                        </tbody>
                                    </table>
                        }
                            </div>
                        </div>
                    </div>
        }
    }

</div>